### ISSUE TITLE
To be done during migration to Production

### ISSUE THREAD

**Issue by kyeap** [Code-Operative/Reuse#94]
The following needs to be done to prevent errors when migrating to production. These are errors encountered while migrating from localhost -> dev server. 

- [ ] change config variables as mentioned in #89 
  - [ ] add ./.htaccess
  - [ ] change DB connection settings: App -> config -> parameters.php 
- [ ] ~~run DB changes migration scripts as mentioned in #86~~
- [ ] ~~fix module as mentioned in #93~~

**Comment by kyeap** [comment]
@renerecalde  @elalelopez i have added this issue to collect all the steps that are required for migration to production. Please fill in anything that you anticipate would be needed as you develop. Thanks!

**Comment by kyeap** [comment]
Advance search module 
- [ ] install advance search module in module catalog
  - this will create the DB needed and also the config necessary e.g. adding required hooks 
 - [ ] make sure [required hooks](https://discord.com/channels/697941369498370128/852566708413267998/877012481233530972) are hooked
